### ISSUE TITLE
Sprite list insert method does not load textures for the sprite

### ISSUE THREAD

**Issue by arnhrwd** [pythonarcade/arcade#1021]
## Bug Report

The sprite list insert method does not load the textures for the sprite, and so the sprite is not visible when using this method to add a sprite to the list.

### Actual behavior:

A sprite inserted into the list is not visible.

### Expected behavior:

The sprite should be visible, the same as when the append method is used.

### Steps to reproduce/example code:
```
self.sprite_list.insert(index,sprite)

self.sprite_list.append(sprite) # Hack to get the insert operation to work
self.sprite_list.remove(sprite) #
self.sprite_list.insert(index,sprite)
```

**Comment by einarf** [comment]
Both coins show up in this quick test
```py
import arcade

class App(arcade.Window):

    def __init__(self):
        super().__init__()
        self.spritelist = arcade.SpriteList()
        s1 = arcade.Sprite(":resources:images/items/coinGold.png", center_x=100, center_y=300)
        s2 = arcade.Sprite(":resources:images/items/coinSilver.png", center_x=100, center_y=400)
        self.spritelist.insert(0, s2)
        self.spritelist.insert(0, s1)

    def on_draw(self):
        self.clear()
        self.spritelist.draw()

App().run()
```

Still need a more concrete scenario when this bug is happening. I did however notice that trying to insert a sprite at an index after `len(spritelist)` can cause some funky behavior. Pushing that fix now into `development` branch.

**Comment by einarf** [comment]
3f9efde1b2292db2f74263f697d4f59b1b2f492f pushed to clamp the insert index so the behavior is similar to `list.insert`.

2.6 had a SpriteList rewrite due to the introduction of texture atlases and this issue seems to have slipped under the cracks. There are a few more things we need to fix to make the new SpriteList easier to work with.

Try with development branch or just `pip install -I https://github.com/pythonarcade/arcade/archive/refs/heads/development.zip`

**Comment by einarf** [comment]
No feedback for 10 days. Marking this as fixed for now. Changes will be added to patch notes.

**Comment by einarf** [comment]
2.6.4 released
