### ISSUE TITLE
Accept hex colour codes when using things like `sprite.color = foo`

### ISSUE THREAD

**Issue by Olliroxx** [pythonarcade/arcade#1022]
### What should be added/changed?

In places like `sprite._set_color` and `arcade.set_background_color`, hex colour codes and uint24s should be supported,

### What would it help with?

Small convenience feature

**Comment by pvcraven** [comment]
```
                if isinstance(color, str) and color.startswith("#"):
                    h = color.lstrip('#')
                    color = [int(h[i:i + 2], 16) for i in (0, 2, 4)]```

**Comment by einarf** [comment]
I think this everything that currently takes a color should still only take the current `Color` type (3 or 4 component list or tuple). If we start broadening this type we'll end up with lots of redudant code aroung in the code base + it will affect performance. There are so many places taking a `Color` currently.

Just adding a utility function for converting a hex string to a tupe is a much simpler approach.

Possibly something like this?
```py
arcade.draw_something(..., color=arcade.color.from_hex_string("#AABBCCFF"))
```

It means the user can also convert the color before the draw call since this conversion is not free. I would also make the function return a tuple as these are faster to work with.
