### ISSUE TITLE
Doc for some functions doesn't generate

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1023]
### What documentation needs to change? 

There are likely more functions like this, but the first example is  [`attempt_font_name_resolution`](https://api.arcade.academy/en/development/api/text_pyglet.html#arcade-attempt-font-name-resolution). There are likely other functions that have this issue as well.

### Where is it located?

At least one of them is here in the source:
https://github.com/pythonarcade/arcade/blob/508f41a076011427e0f09b246c6e79851d244968/arcade/text_pyglet.py#L39-L53

I am not sure where the others are if they exist.

### What is wrong with it? How can it be improved?

The docstrings aren't rendered by sphinx despite existing. They should be.

**Comment by pushfoo** [comment]
the heuristic function in pathfinding may be another, but in that case the issue is clearer since it looks like the docstring only consists of malformed sphinx directives:

https://github.com/pythonarcade/arcade/blob/508f41a076011427e0f09b246c6e79851d244968/arcade/paths.py#L59-L68

**Comment by pvcraven** [comment]
These aren't showing up because they aren't in the `__init__.py`. We need to do one of the following:

* Include them as part of Arcade
* Pre-pend them with an underscore and make them internal only.

The following items need attention:
* build_cache_name
* attempt_font_name_resolution
* PymunkException
* heuristic

**Comment by einarf** [comment]
2.6.4 released
