### ISSUE TITLE
Implement Global Alpha for Sprites in SpriteList

### ISSUE THREAD

**Issue by rckwzrd** [pythonarcade/arcade#1056]
## Enhancement request:

Implement Global Alpha for Sprites in SpriteList.

### What should be added/changed?

Allow SpriteList to access and modify alpha property of all Sprites contained in list.

### What would it help with?

Quickly changing transparency of common Sprites collected in a SpriteList. Avoids explicitly looping over Sprites in list to adjust alpha.

**Comment by einarf** [comment]
There are two ways to approach this.

1) Make an optimized method that loops each sprite setting alpha values
2) Create a version of the sprite shader that applies a global alpha

Version 1 is probably the safest because the alpha will still be stored in the sprites and we avoid state confusion. The downside is that it's less efficient. It would acceptable for a smaller amount of sprites, but it several thousands we will run into problems.

**Comment by Cleptomania** [comment]
I would think option 2 would be a better avenue to take in the long run, though we could probably just add an optimized method for the immediate term. I’ve seen this requested a number of times on discord.

**Comment by einarf** [comment]
We can just do `texture_color * sprite_color * spritelist_color` to get both solutions I guess?

**Comment by einarf** [comment]
Added in d8c7b7081566f6c61c41f41de56841db295fb684
![alpha](https://user-images.githubusercontent.com/5418180/147893497-129c3284-ca47-4db7-95d9-fc1c835f6eca.gif)

**Comment by rckwzrd** [comment]
this is awesome!

has it been released?

if so, does the issue need to be closed?

**Comment by einarf** [comment]
@mlr07 Not released yet, but you can pip install arcade development branch for now. It will be closed when next bug release is out.

**Comment by einarf** [comment]
2.6.10 released
