### ISSUE TITLE
Support arcade in headless mode

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#1107]
Pyglet have support for headless mode though EGL. This will only work on linux, but it's a good start allowing users to run arcade applications on linux servers.

@gaorkl requested this feature and started experimenting with some success: https://github.com/gaorkl/hlarcade

It seems to be somthing we can achieve without too much trouble, but we might need a different entrypoint for this. Headless don't have window or other input events, so the interface is pretty simple.

**Comment by gaorkl** [comment]
Hi!

I have been doing small experiments.
Turns out that if I add this to the `__init__.py` of arcade :
```python
if not pyglet.options['headless']:
   from .joysticks import get_game_controllers 
   from .joysticks import get_joysticks 
```
Then I can load sprites.
So it might be a very quick fix, but I am not sure which features will be unavailable in headless mode.

I am adding a headless context class and creating a PR to see if it is suitable.

Cheers

Michael

**Comment by gaorkl** [comment]
Turns out Arcade and Pyglet are interacting very well.
Once the headless option is set, Arcade automatically creates headless windows.
So, basically, we just need to add some cases in the arcade code to avoid trying to import modules that depend on a physical window (e.g. joystick, mouse, etc).
But, It works.

**Comment by gaorkl** [comment]
I just submitted a PR #1110 
The tests are nearly all passing on my server.

**Comment by einarf** [comment]
Awesome. I will try to get this merged and resolved during the weekend.

**Comment by gaorkl** [comment]
Hi!
The only thing I didn't manage to do was starting the tests in headless mode.
That is, even if you have a display, start as if you are on a server (using headless option in arcade).
I will try that today see what happens.

**Comment by einarf** [comment]
I think all should be working now. I threw together this one quickly : https://api.arcade.academy/en/development/advanced/headless.html

Might be more info needed there. Please review if you can. All is in development branch now.

**Comment by einarf** [comment]
2.6.13 released
