### ISSUE TITLE
GUI: Some widgets are still using `arcade.draw_text`

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#1138]
This really affects the performance when re-rendering the widgets. A worst case 100x cost compared to using a persistent `Text` or `pyglet.text.Label` instance.

**Comment by pushfoo** [comment]
It looks like there are only 2 items remaining, and they're in `arcade/gui/buttons.py`. I don't see an elegant way to remove them yet since we'd need a way to update the text object when certain style attributes are changed. This might become clearer after I use the GUI event and property systems more.

**Comment by einarf** [comment]
A quick search shows that this is already fixed
