### ISSUE TITLE
Ability to exclude built-in assets from pyinstaller build

### ISSUE THREAD

**Issue by DragonMoffon** [pythonarcade/arcade#1141]
## Enhancement request: 
A version of Arcade that does not contain all of the examples, and resources.

### What would it help with?
making packaged versions of Arcade games smaller. Since it would remove all of the unnecessary examples and Kenny assets.

**Comment by einarf** [comment]
Since we are talking about the packaged version or arcade it's fairly easy to modify the pyinstalled hook : https://github.com/pythonarcade/arcade/blob/development/arcade/__pyinstaller/hook-arcade.py

Maybe we can add some enviroment variables for excluding examples and redundant resources + experimental? We can easily just split `resources` into the core and extra ones, but we have to make sure the resource path is the same as before so we don't break code.

I suggest keeping `:resources:` and create a new handle for all the core things like shaders and default fonts.

**Comment by Cleptomania** [comment]
This is much more possible to do now, the assets/system resources are split up now, we should be able to easily add an environment variable to the pyinstaller hook to exclude the built-in assets now that they're splitup.

**Comment by Cleptomania** [comment]
This is finished now. The pyinstaller hook by default excludes the built-in example resources and only includes the `system` resources folder. There isn't an in-built way to make pyinstaller include the built-in resources, however that can easily be added on the end user side and is likely not a big deal so I think it's fine the way it is. If we notice problems we can maybe add an environment variable or something to enable including them, however I think not including them by default is a sane default.

Most people I've encountered distributing packaged builds of their games are not using example assets from us.
