### ISSUE TITLE
Better compliance with pyright

### ISSUE THREAD

**Issue by the-argus** [pythonarcade/arcade#1207]
## Enhancement request:
Change code format to better allow for autocompletion and type checking by the pyright language server.

### What should be added/changed?
For starters, the Color.COLORNAME constants are unrecognized by pyright and I'd like to be able to autocomplete them.

### What would it help with?
The speed at which developers are able to make the simple arcade games that arcade is so good at allowing us to make with ease.

### Note
I would be willing to make a PR for this, *at some point*. Busy at the moment but it should be pretty simple.
Also: are you currently trying to comply with other langservers/linters/formatters that doing this would conflict with?

**Comment by Cleptomania** [comment]
I'm not 100% certain of compatibilities between stuff here, but this is what we're currently using:

Mypy and flake8 are the only thing that's actually being enforced by CI currently and used by default by most everyone developing. However we are to some extent using black, we have some issues around auto-formatting certain pieces of code due to being imported directly into examples and documentation the auto-formatting process can throw that off by modifying line numbers that we didn't take into account.

There are ways around this and we've discussed it, and maybe at some point in the future will be using Black by default and enforcing it in CI, however that needs some more work before it can be a thing. So while Black is not actually enforced right now, I don't think we want to make any moves that would prevent it from being used.

I am guessing if anything is incompatible here it would be mypy, but I don't have any experience with pyright myself and so I can't speak to exactly how well both could be supported.

I think that if it's possible to support it fully without interrupting any of the above tools then I'd see no problem with a PR for it.

**Comment by einarf** [comment]
Do you know why they are unrecognized? Small code snippet showing how a color us used? Are you importing specific colors or the color modules separately? Maybe it relies on `__all__`?

**Comment by Hunter2809** [comment]
![image](https://user-images.githubusercontent.com/46440327/174109361-5b92bc34-9025-485b-a678-5905e4eb96c0.png)
As u can see, the autocomplete works in Visual Studio Code, using Pylance which uses Pyright under the hood @the-argus 

> For starters, the Color.COLORNAME constants are unrecognized by pyright and I'd like to be able to autocomplete them.

All the colors are in a submodule named `color`, not the Color class. Probably that is the issue you are facing

**Comment by einarf** [comment]
Closing this for now. We do contributors using pyright. For this specific issue I think it's a misunderstanding that Color or an enum, but it's just a type alias.

If you think this a mistake, be free to reopen.
