### ISSUE TITLE
Is .tmx still supported?

### ISSUE THREAD

**Issue by brccabral** [pythonarcade/arcade#1236]
Hi,
`arcade.read_tmx()` has been deprecated. TileMap loads .json files. Is .tmx still supported? How to load a .tmx file?

**Comment by Cleptomania** [comment]
So the various versions of Arcade and what they supported in terms of Tiled maps are a bit all over the place:

Pre 2.6.0 - Only supported TMX with a somewhat limited feature set
2.6.0 - 2.6.8 - Only supported JSON but had near 100% feature coverage with Tiled
2.6.9 and above - Supports both JSON and TMX interchangeably via the same API. No API changes since 2.6.0, just additional ability to process the TMX files as well.

As it stands today on the current version, you can use both maps types by passing it to `arcade.load_tilemap()` function. You can even intermix formats, so you can have a TMX map with a JSON tileset, or a JSON map with a TSX tileset, and it will auto-detect the formats and handle them accordingly.

For an example see this page: https://api.arcade.academy/en/latest/examples/sprite_tiled_map.html#sprite-tiled-map

I would recommend if it's possible or not too much effort, that JSON is the preferred format. There's nothing wrong with TMX and we will generally support both, but more advanced features in the future and such are more likely to see support for the JSON format first, with TMX being added later on(if at all, depending on the feature)

**Comment by brccabral** [comment]
Thank you @Cleptomania 
I was having problems with an imported tilemap, but I was able to fix it.
