### ISSUE TITLE
Enhancement: Tiled Alternative (Construct3).

### ISSUE THREAD

**Issue by Abhishek10351** [pythonarcade/arcade#1245]
## Enhancement request:

You can add a new module/plugin to parse .c3p files made using [Construct3](https://www.construct.net/en) .

It would help in using a alternate application for **Tiled** maps and give developers a option to chose from.

**Comment by einarf** [comment]
Do they describe the file format somwhere?

We do also take PRs or an external module can be created.

**Comment by pushfoo** [comment]
capx seems to be the format for construct 2 [according to this forum post](https://www.construct.net/en/forum/construct-3/how-do-i-8/save-project-capx-149385). It also seems to be the entire project folder as a zip, not a specific map format.

**Comment by pushfoo** [comment]
Although the issue was edited to mention .c3p instead of Construct 2 capx, [c3p files are also zips of the project folder](https://www.construct.net/en/make-games/manuals/construct-3/overview/saving-projects#internalH1Link3).

However, there are some problems with implementing this in arcade:
1. Their storage formats do not appear to be publicly documented, requiring additional work to understand them beforehand
2. Construct 3 isn't open source, so implementing this feature doesn't align with arcade's purpose as part of a free and open source ecosystem of game development tools useful for education 

The good news is that you might be able to implement this yourself. Construct 3's [TileMap](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/tilemap) documentation mentions the ability to save to JSON. It's possible that Construct 3 uses JSON to store project data in general. 

To get started, you should try opening .c3p files as zips to understand how the data is stored. If the data you want to use is in fact stored as JSON, you can do the following to automate c3p loading:
1. Open .c3p files using Python's [`zipfile` module](https://docs.python.org/3/library/zipfile.html)
2. Use Python's [`json` module](https://docs.python.org/3/library/json.html) to load the extracted data into more usable form
