### ISSUE TITLE
Adding Object—Oriented Shapes

### ISSUE THREAD

**Issue by eschan145** [pythonarcade/arcade#1268]
### Enhancement Request
It could be useful to add purely object-oriented shapes to display, creating by defining a new `Shape` object instead of calling a function (see `arcade.buffered_draw_commands`) One problem with the current object-oriented shapes is that many properties cannot be changed after creation (eg. a `radius` property for circles, a `color` property, `width`, etc.)

**Comment by pushfoo** [comment]
To my understanding, the long-term goal for shapes is to increase pyglet interoperability since [pyglet already implements mutable OOP shapes](https://pyglet.readthedocs.io/en/master/modules/shapes.html). You may be able to use pyglet's shapes with arcade right now by using the [`arcade.ArcadeContext.pyglet_rendering`](https://api.arcade.academy/en/latest/api/open_gl.html?highlight=pyglet#arcade.ArcadeContext.pyglet_rendering) function. You should probably use batches for rendering your shapes as pyglet recommends. They're somewhat similar to the SpriteList and ShapeElementList you have already seen in arcade.

**Comment by einarf** [comment]
Yup. In 2.7 you should be able to use pyglet shapes. Those are object oriented.

We might look into improving arcade's shape system in the future, but right now there are more important things to focus on.
