### ISSUE TITLE
ZeroDIvisionError raised when screen dimensions equal zero

### ISSUE THREAD

**Issue by eschan145** [pythonarcade/arcade#1276]
When you resize any arcade window's dimensions so only the toolbar is visible:
```
sy = 2.0 / height
ZeroDivisionError: float division by zero
```

**Comment by einarf** [comment]
Does this exepction happen in your code or arcade code? Please share the entire stack trace.

**Comment by eschan145** [comment]
Any arcade code raises this error. Just if the window's resizable parameter is set to true.

**Comment by einarf** [comment]
You should use `set_minimum_size(..)` on the window to avoid this. Maybe we should set a default minimum size. on creation. Would that solve the issue?

**Comment by pushfoo** [comment]
Many Linux window managers & wayland compositors support "rolling up" a window to its title bar alone. That could plausibly set the window size to 0, so allowing windows to be set to 0 height is behavior we should still allow for somehow. It's especially relevant if we build the GUI toolkit up to the point that people can start writing tools in arcade. 
Since this is an advanced usecase and it's not certain that window roll up sets height to 0, we could go with a default minimum size on windows and mention advanced usage somewhere in the doc.

**Comment by einarf** [comment]
Fixed now. Thanks for reporting. We simply don't update the projection matrix internally when window width or height is zero.

Users specifying their own matrices with Mat4 will have to handle this on their own.
