### ISSUE TITLE
Text should not modify the view matrix

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#1290]
In arcade 2.6 and ealier the view matrix only affected pyglet text. in 2.7 it affects everything.

We need to make sure:
* Text is affected by the current view matrix. This might mean doing a matrix multiplicaiton.
* Text can still be rotated and translated using a local matrix

**Comment by Cleptomania** [comment]
I believe this is fixed in 2.7 after adding native rotation to Text in pyglet and the work to let Text objects use pyglet batches. We are no longer using the view matrix to do rotation for it, it is handled internally in the text shaders in Pyglet.

I'm going to close this as I believe it's no longer an issue, if someone knows differently feel free to re-open
