### ISSUE TITLE
Can't set update_interval

### ISSUE THREAD

**Issue by markuspinter** [pythonarcade/arcade#1336]
## Cannot set update_interval / gets ignored!

Hi, I'm trying to setup a Window for drawing a simple texture on it. Just out of curiosity I've printed my current FPS.
Weirdly it is frame locked to 60 fps. I've looked it up and it seems to be changeable by either

- calling self.set_update_interval(1/<max_fps>) or by
- setting it directly inside the super __init__ function

but neither of these methods change the behavior. 
Am I missing another function call?

Thanks for your help!

I'm on macOS Monterey 12.5.1

This is my code:

```
"""
Starting Template

Once you have learned how to use classes, you can begin your program with this
template.

If Python and Arcade are installed, this example can be run from the command line with:
python -m arcade.examples.starting_template
"""
import arcade

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "Starting Template"


class PPU(arcade.Window):
    """
    Main application class.

    NOTE: Go ahead and delete the methods you don't need.
    If you do need a method, delete the 'pass' and replace it
    with your own code. Don't leave 'pass' in this program.
    """

    def __init__(self, width, height, title):
        super().__init__(width, height, title, update_rate=1/120, vsync=False, antialiasing=False)

        arcade.set_background_color(arcade.color.AMAZON)
        arcade.enable_timings()
        self.offsetX = 0
        self.offsetY = 0

        # If you have sprite lists, you should create them here,
        # and set them to None

    def setup(self):
        """ Set up the game variables. Call to re-start the game. """
        # Create your sprites and sprite lists here
        pass

    def on_draw(self):
        """
        Render the screen.
        """

        # This command should happen before we start drawing. It will clear
        # the screen to the background color, and erase what we drew last frame.
        self.clear()


        # --- Drawing Commands Will Go Here ---
        arcade.draw_text(f"FPS: {arcade.get_fps()}", 3, 3, arcade.color.BLACK, 12)

        # # Draw the face
        # x = 300+self.offsetX
        # y = 300+self.offsetY
        # radius = 200
        # arcade.draw_circle_filled(x, y, radius, arcade.color.YELLOW)

        # # Draw the right eye
        # x = 370+self.offsetX
        # y = 350+self.offsetY
        # radius = 20
        # arcade.draw_circle_filled(x, y, radius, arcade.color.BLACK)

        # # Draw the left eye
        # x = 230+self.offsetX
        # y = 350+self.offsetY
        # radius = 20
        # arcade.draw_circle_filled(x, y, radius, arcade.color.BLACK)

        # # Draw the smile
        # x = 300+self.offsetX
        # y = 280+self.offsetY
        # width = 120
        # height = 100
        # start_angle = 190
        # end_angle = 350
        # arcade.draw_arc_outline(x, y, width, height, arcade.color.BLACK,
        #                         start_angle, end_angle, 10)

        self.offsetX = (self.offsetX + 10) % SCREEN_WIDTH
        self.offsetY = (self.offsetY + 5) % SCREEN_HEIGHT

    def on_update(self, delta_time):
        """
        All the logic to move, and the game logic goes here.
        Normally, you'll call update() on the sprite lists that
        need it.
        """
        pass

    def on_key_press(self, key, key_modifiers):
        """
        Called whenever a key on the keyboard is pressed.

        For a full list of keys, see:
        https://api.arcade.academy/en/latest/arcade.key.html
        """
        pass

    def on_key_release(self, key, key_modifiers):
        """
        Called whenever the user lets off a previously pressed key.
        """
        pass

    def on_mouse_motion(self, x, y, delta_x, delta_y):
        """
        Called whenever the mouse moves.
        """
        pass

    def on_mouse_press(self, x, y, button, key_modifiers):
        """
        Called when the user presses a mouse button.
        """
        pass

    def on_mouse_release(self, x, y, button, key_modifiers):
        """
        Called when a user releases a mouse button.
        """
        pass


def main():
    """ Main function """
    ppu = PPU(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE)
    ppu.setup()
    arcade.run()


if __name__ == "__main__":
    main()
```

And this is my Window:

![Screen Shot 2022-09-27 at 1 17 43 AM](https://user-images.githubusercontent.com/17620292/192397358-ece4b0a9-8ccc-4e34-8eb8-04d087910e4a.png)

**Comment by Cleptomania** [comment]
Hi, thanks for the report. We actually already discovered this issue previously, and it has since been fixed in our `development` branch and will be part of an upcoming 2.7 release.

This happens because of the underlying event loop in Pyglet, in Pyglet this system changed to accepting a parameter for the draw rate, and defaults to `1 / 60`(aka 60 FPS). Prior to the version of Pyglet used in Aracde 2.6, it would simply run it as fast as possible. We missed the change in behavior during the original 2.6 release of Arcade.

In the development branch of Arcade, the way to handle this is by setting the `draw_rate` parameter of the Window constructor, however since this doesn't exist in Arcade 2.6, a work-around is to call `pyglet.app.run(1 / 120)` instead of calling `arcade.run()`, this example should give you an FPS limit of 120. The arcade run function is just a wrapper over top of the Pyglet one.

It would be possible to backport this `draw_rate` parameter to a 2.6 version of Arcade, but I'm unsure if that is going to happen right now or not, as we are approaching the 2.7 release.

Let me know if the workaround above works for you, if it doesn't you can also optionally install Arcade from the development branch here on Github and use the new `draw_rate` parameter(though there are potentially other breaking changes you may need to handle with using 2.7, depending on what all your application uses).

As an additional clarification, the update rate parameter you've described in the issue is exclusive to the `on_update` event, so the speed at which `on_update` and `on_draw` are called can vary.

**Comment by markuspinter** [comment]
Works perfectly!

Thank you very much.
