### ISSUE TITLE
Assert used in production code

### ISSUE THREAD

**Issue by gran4** [pythonarcade/arcade#1800]
## Bug Report

assert in production code
line 100, /arcade/text.py
`assert isinstance(label, pyglet.text.Label)`

**Comment by einarf** [comment]
I don't think this is a big deal. We have `assert` and `__DEBUG__` checks in many other placesin arcade. Using these to sanity check types of incoming paramters is not a terrible idea if it increases the usability of the library.

One can argue it's not really necessary here since this is a private function.
