### ISSUE TITLE
Revert __future__ import in all examples

### ISSUE THREAD

**Issue by cspotcode** [pythonarcade/arcade#1888]
In #1859, I added `from __future__ import annotations` to all files.  I should not have added this to the examples.

I should make a follow-up PR to revert the modifications to `arcade/examples`

https://github.com/pythonarcade/arcade/pull/1859/commits/ddf8c8cb441a403e340f610bb03b5431c5e1c190

**Comment by pushfoo** [comment]
Should this be reverted in `tests/unit/test_key.py` as well? Both #1892 and #1892 will fail CI because the annotations import adds another member.

Other options include changing that test:
1. Regex-based with `inspect.getsource`: `^([A-Z][A-Z0-9]+)\ \=\ [0-9]+$`
2. `inspect.getmembers`, but this adds some noise from `__loader__` and `__spec__`
