### ISSUE TITLE
Unit test on a View

### ISSUE THREAD

**Issue by deangelisdf** [pythonarcade/arcade#1904]
Hi all,
Do you have some method to test the code implemented for a View?
The issue to my side seems the inability to mock the window.

Thanks in advance
Domenico

**Comment by pushfoo** [comment]
Can you please provide more details about the following?

1. Are you trying to add unit tests to arcade, or to your own code subclassing view?
2. What specific behavior are you trying to test?
3. Do you have a repo posted anywhere for reference, or code which demonstrates an example of the problem?
4. What do you mean by "seems the inability to mock the window"?
5. Which arcade version and platform are you on?

We don't have helper classes or functions specific to unit testing view. Also, the unit test style for arcade may differ from what you're used to. The unit tests for arcade are intentionally simple avoid more complex features as a way to keep tests accessible to beginners.

For your own projects, there should be no problem with using mocks or other techniques, except when it runs up against inherent limitations.

**Comment by deangelisdf** [comment]
Hi,

1. I reliazed a View subclass
2. I'm trying to test the business logic (if it is not possible, next step i thought is to decouple code)
3. https://github.com/deangelisdf/visual_novel_pyarcade/blob/main/graphic_novel/__init__.py
3.a. I did also some UT but cannot execute by GITHUB_ACTIONs as https://github.com/deangelisdf/visual_novel_pyarcade/blob/main/tests/actions_test.py
4. I can't use arcade without a window. So, I tried using Mock from unittest to replace it with window, the thing is that the class that is used below is complex and it is not worth adapting it by using a mock.
5. I'm testing on windows 10, but i want try to execute the test on remote (with github_action)

Thanks,
I'll read the arcade python tests

**Comment by pushfoo** [comment]
Thank you for providing source links and additional details.

> I'll go to read arcade python tests

Don't spend too much reading them. Arcade currently [runs tests with a real Window on a maintainer's computer](https://github.com/pythonarcade/arcade/blob/development/.github/workflows/selfhosted_runner.yml). It's unreliable and [there's an open ticket to fix it](https://github.com/pythonarcade/arcade/issues/1776#issuecomment-1550137871). I'm not sure what the status of that was.

> I did also some UT but cannot execute by GITHUB_ACTIONs as

The fastest route to working CI for your project may be use the traditional approach pyglet still uses: [use xvfb to run headlessly](https://github.com/pyglet/pyglet/blob/09ac9a590dadae282767e3831df6945f90d4be12/.github/workflows/unittests.yml#L5-L25
). 

| Advantages |  Disadvantages |
| -- | -- |
| <ol><li>Reliable, battle-tested by Selenium Grid users</li><li>Allows pixel-testing integration tests</li></ol>|<ol><li>Slower CI runs</li><li>Relying on apt adds an extra point of failure</li><li>Impure unit tests mean drawing code can cause init / property code to fail</li></ol>|

There is [a shader getter fixture](https://github.com/pyglet/pyglet/blob/09ac9a590dadae282767e3831df6945f90d4be12/tests/unit/conftest.py#L7-L35) in pyglet which helps keep unit tests for some classes pure, but it's still clumsy. I aim to replace with an automatic shader mock system [as I outlined here](https://github.com/pyglet/pyglet/issues/953#:~:text=also%20be%20helpful.-,Why%20Mock%20Shaders%3F,-It%27s%20for%20a). However, that can't help you yet:

1. It's not ready
2. It would need to be rewritten for arcade since at least some of arcade's shader-related GL binding is custom-built and independent of pyglet
3. It might be too much "magic" to fit with arcade's beginner-friendly test style

**Comment by deangelisdf** [comment]
Thanks @pushfoo
Your help has been invaluable. I will start with studying the mockups used on pyglet.
If it helps I will update you on the results.
