### ISSUE TITLE
create_ellipse_outline only works for a line width of 1

### ISSUE THREAD

**Issue by pvcraven** [pythonarcade/arcade#729]
`arcade.create_ellipse_outline` gives an assertion error if line width parameter is anything but 1.

**Comment by einarf** [comment]
Yup. This is in the `Shape` class itself. It's nothing we have modified this year at least. I think the assert was added because `glLineWidth` doesn't work in GL 3.3 core (but works in compatibility contexts). We are meant to use geometry shader to create wide lines. Fixing this is part of the `ShapeElementList` revamp.

**Comment by pvcraven** [comment]
Still an issue.

**Comment by einarf** [comment]
There is no longer an assert at least.

**Comment by einarf** [comment]
There is no longer an assert. The argument is simply ignored now. We want to piggyback on pyglet shapes instead of maintaining the current shapy system, so let's just close this.
