### ISSUE TITLE
Autoformat Arcade using Black

### ISSUE THREAD

**Issue by benjamin-kirkbride** [pythonarcade/arcade#738]
I really like the [Black](https://github.com/psf/black) code formatter, and think it would benefit this (and any) project to use it.

Is this something that we would be open to? If so, I could prepare a pull request that `black`s the existing codebase, and add it as a dev dependency, so we could see what that would look like?

**Comment by einarf** [comment]
I've formatted most of the `arcade.gl` module using black. Definitely like it.

**Comment by eruvanos** [comment]
I just started using black a few days ago, have to change my behavior to use double quotes, but already getting used to it.

**Comment by Cleptomania** [comment]
I've been experimenting with this through my update of the Sound module.

From what I've noticed, the main problem with Black formatting is that it is very adamant about imports happening before anything else. Due to the nature of a number of things in the library, there are some instances where code needs to run before importing something.

For example, in order to load ffmpeg binaries properly within the new sound update. The binaries must be added to the system path before Pyglet is imported.

I'm sure this could be overcome through configuration of some sort, but something to think about.

**Comment by Cleptomania** [comment]
We've since landed on a philosophy of "format as we go" with regard to modules within Arcade's codebase.

However have decided that auto-formatting should not be used on example code as the docs do specific highlighting and/or mentioning of line numbers and auto-formatting can very easily unintentionally break that.
