### ISSUE TITLE
Error soloud on MacOS High Sierra 10.13.6

### ISSUE THREAD

**Issue by diablo76600** [pythonarcade/arcade#745]
## Error

Hello,

i have this error on MacOS High Sierra 10.13.6 :
**Warning, can't initialize soloud name 'soloud_dll' is not defined. Sound support will be limited.**

Tanks

**Comment by einarf** [comment]
@Cleptomania is working on improving this 😄 

You can use `pyglet.audio` as a replacement for now. It's fairly competent and playing pre-loaded staticsources using wav files.

**Comment by diablo76600** [comment]
Thank you
But all my music is in mp3..... :-(

**Comment by Cleptomania** [comment]
I am currently in the process of re-writing the sound engine to support multiple backends and hopefully expand cross-platform support in that way.

Pyglet has lack-luster support for audio on MacOS out of the box, but it works well if you have ffmpeg installed on your system. If you want to attempt to use Pyglet instead, you should be able to load mp3 files fine so long as ffmpeg is installed. Pyglet will automatically look for an ffmpeg installation.

My updates to the Sound module in Arcade will be allowing for Pyglet or Soloud to be used based on a configuration option. With soloud being the default and automatically falling back to Pyglet if it fails to initialize soloud. The main drawback of Pyglet at this stage is the MacOS support, but like I said with ffmpeg that problem is solved, however I am looking into the possibility of adding a CoreAudio driver to Pyglet to reduce the need for external dependencies.

I am expecting to have a PR in for the multiple backends and initial Pyglet audio support in Arcade this weekend.

**Comment by diablo76600** [comment]
Yes it works well if ffmpeg is installed 👍 .
`brew install ffmpeg`

https://youtu.be/XkGqRQP19Vc

**Comment by Cleptomania** [comment]
@diablo76600 Just so you're in the loop on this. My re-write is using Pyglet with ffmpeg, and the binaries for ffmpeg will be shipped inside of Arcade. So you will be able to use Arcade's sound module in the same manner it previously was on Windows, Mac, and Linux with .wav, .mp3, and .ogg files.

I've submitted the pull request for that feature here #746

**Comment by pvcraven** [comment]
Arcade has dropped soloud and now using pyglet's audio.
