### ISSUE TITLE
Installing arcade with python 3.9.1 gets arcade version 2.4.3

### ISSUE THREAD

**Issue by MrGallo** [pythonarcade/arcade#807]
Problem changed to: Poetry installed arcade 2.4.3 on my system. I think this is because I'm running Python 3.9.1

Previously:
A fresh install of Arcade is installing `pymunk` version `6.0.0` and causes the following error:

```
Traceback (most recent call last):
  File "d:\danga\Documents\GitHub\academy\examples\arcade_test.py", line 13, in <module>
    import arcade
  File "C:\Users\danga\AppData\Local\pypoetry\Cache\virtualenvs\academy-K9LK73SA-py3.9\lib\site-packages\arcade\__init__.py", line 103, in <module>
    from .drawing_support import calculate_hit_box_points_detailed
  File "C:\Users\danga\AppData\Local\pypoetry\Cache\virtualenvs\academy-K9LK73SA-py3.9\lib\site-packages\arcade\drawing_support.py", line 7, in <module>
    import pymunkoptions
ModuleNotFoundError: No module named 'pymunkoptions'
```

Looking at the [newest version of `pymunk`](https://buildmedia.readthedocs.org/media/pdf/pymunk/latest/pymunk.pdf) they removed `pymunkoptions`. I needed to downgrade pymunk to `=="5.7.0"` to get arcade to work.

`import pymunkoptions` is found in:

```
arcade\drawing_support.py - line 7
arcade\pymunk_physics_engine.py - line 5
```

**Comment by pvcraven** [comment]
I swear the most recent release was pinned to 5.7.0. What on Earth?

**Comment by pvcraven** [comment]
In release 2.5.1 it looks to be pinned to 5.7 of Pymunk.

**Comment by MrGallo** [comment]
So Poetry installed arcade `2.4.3` on my system. I think this is because I'm running Python `3.9.1`.

Trying to force `arcade=="2.5.1"` results in:

```
$ poetry add arcade=="2.5.1"

Updating dependencies
Resolving dependencies...

  SolverProblemError

  The current project's Python requirement (>=3.9,<4.0) is not compatible with some of the required packages Python requirement:
    - arcade requires Python >=3.6,<3.10, so it will not be satisfied for Python >=3.10,<4.0

  Because academy depends on arcade (2.5.1) which requires Python >=3.6,<3.10, version solving failed.

  at c:\users\danga\appdata\local\programs\python\python39\lib\site-packages\poetry\puzzle\solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

    For arcade, a possible solution would be to set the `python` property to ">=3.9,<3.10"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```

**Comment by rubiconjosh** [comment]
Poetry will not let you use Arcade 2.5.2 because it requires Python >= 3.6, <3.10.
https://github.com/pythonarcade/arcade/blob/development/setup.cfg#L33

Your pyproject.toml looks like this: 
```
[tool.poetry.dependencies]
python = "^3.9"
```
Even thought you currently have python 3.9.1 your poetry settings will allow it to be updated to 3.10, that would conflict with the <3.10 requirement from arcade.

If you look at the setup.cfg from the arcade 2.4.3 release there is no python_requires setting. That is why poetry is okay with the older release.
https://github.com/pythonarcade/arcade/blob/release_2_4_3/setup.cfg

When I use `poetry add arcade` it does not substitute arcade 2.4.3, it just fails for 2.5.2. I do not know why it downloaded the older version for you. Did you use the poetry add command or manually put arcade in the pyproject.toml?

The output from the command gives a solution for you, edit pyproject.toml as follows:
```
[tool.poetry.dependencies]
python = ">=3.9,<3.10"
```

I am not sure how many other people may be experiencing this issue. It brings up a point for consideration.

Should arcade change python_requires to "^3.6"?

**Comment by pvcraven** [comment]
Problem is when Python upgrades, and libraries we depend on aren't ready yet. Then we allow an Arcade install, and can't run because Pillow or Numpy aren't ready. Ideally, no install would be allowed.

Unfortunately, the actual result is that it goes back versions until it finds one before we put in this fix. I'm not sure how to get to the better 'don't install' solution.

**Comment by MrGallo** [comment]
@rubiconjosh Thanks for clarifying the poetry output for me. I understand what it says now.
