### ISSUE TITLE
need method to save the tmx map file

### ISSUE THREAD

**Issue by pyweeker** [pythonarcade/arcade#861]
Hello,
i was happy to load tmx files to start the game,
how can i save map modifications inside the tmx file ?

**Comment by Cleptomania** [comment]
If you’re talking about modifying a map at runtime and then re-saving the map file with the changes, that is not something we currently support. If we did add support for this it would be very far down the line, it would require a relatively large extension to pytiled-parser to make this possible.

Ontop of the heavy lift to pytiled-parser, it would also require a ton of glue code in Arcade because everything is converted to Arcade objects(like Sprite for example), so you’d have to reverse that entire process to extract the necessary info and convert it into a pytiled-parser type.

**Comment by pyweeker** [comment]
quick answer thank you Cleptomania, any idea for a dirty hack if the map is not too complex ?

**Comment by Cleptomania** [comment]
Depends exactly on what you’re changing, the best way I can think of is to create your own kind of save file format with JSON or something, and load that in at setup after the map and everything has been created. It would be a decent bit of work to create such a system depending on what type of objects you’re wanting to save like this is though, unfortunately I don’t really see a quick and simple way to handle this kind of feature.

**Comment by pyweeker** [comment]
thank you !
