### ISSUE TITLE
improving tilemap.process_layer.py to facilitate map savegame recording

### ISSUE THREAD

**Issue by pyweeker** [pythonarcade/arcade#870]
## Problem = lack attribute inside sprite object to save it easily
After having loaded a map made with tiled, i want to  save game.
What i need is to loop on all my sprite_list, each sprite knows his x,y position i can translate in grid coordinates inside json file.
But it's difficult for a sprite to know which integer value represent himself when he will be saved.
Lets look an example map made with software tiled.

I mean inside map , we have a dict which contains layers key which is a list of dict. The value inside key **data** is  precious 

_"data":[0, 0, 0, 0, 0, 0,2,2,2,5,0,0]_

I used this cmd to convert from tmx to json, 
**tiled --export-map mymap.tmx mymap.json**

here is the result:

```
{ "compressionlevel":-1,
 "editorsettings":
    {
     "export":
        {
         "format":"tmx",
         "target":"mymap.tmx"
        }
    },
 "height":10,
 "infinite":false,
 "layers":[
        {
         "data":[0, 0, 0, 0, 0, 0,2,2,2,5,0,0],
         "height":10,
         "id":2,
         "name":"Platforms",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":10,
         "x":0,
         "y":0
        }, 
       etc...
```
### Actual behavior:
When instanciating sprite from loading the corresponding layer
inside tilemap.process_layer , it forks between **_process_tile_layer** and **_process_object_layer**.
inside them, they call **_create_sprite_from_tile**.
### Expected behavior:
I failed to make working the injection of the wished integer attribute to find back the corresponding png file .
On the same layer, you can have same behaviour object but with other look. Or different kind of items.

I tried to tinker decorators, add custom method and replace calls but i failed.
```
new_index = column + (row * grid_width)
for spritelist in mega_spritelist:
    new_layer = spritelist.give_jsondict()
    for sprite in spritelist:
        new_layer["data"][sprite.new_index] = sprite.attribute_i_need
    jsonobject["layers"].append(new_layer)
```

something like this ;-)
Making a dict from texture.image seems ugly hack. 

An idea for optimizing:
Some layers won't change (like walls_list) or we do not want to save them (ie bullets_list), maybe it's possible to designate which sprites_list need to be saved (with maybe a decorator like **@save_it** ? )

**Comment by Cleptomania** [comment]
In the upcoming 2.6 release of Arcade the tilemap module and the underlying map parser library pytiled-parser have both been completely re-written.

When 2.6 comes out you would have access to everything you’d need to re-save a Tiled file, but in order to save the map in a way that can be re-loaded using the same system, the entire map needs saved regardless of what has changed. So if you were going to implement this yourself you would need to fully implement 100% of the tiled map format spec, otherwise it will likely fail to load.

pytiled-parser(which I maintain now) would need a pretty extensive amount of work done to make this possible to do, and while it is a feature I’d like to have, probably isn’t some I see myself getting to for at least several months if even this year.

Ontop of the work needed in pytiled-parser to make this possible, some kind of conversion utility within Arcade would need written to bridge the gap back from Sprites to Tiled objects. It goes beyond just knowing the tile and coordinates that each Sprite is. We have to re-save literally everything in order to make the map file possible to reload through the tilemap system.

**Comment by pyweeker** [comment]
thank you Cleptomania

**Comment by pyweeker** [comment]
i did it !!!!!
come help me to upgrade it !
[https://github.com/pyweeker/sarkadban](https://github.com/pyweeker/sarkadban)
