### ISSUE TITLE
Arcade does not support pyinstaller on Mac yet... Okay but why? 

### ISSUE THREAD

**Issue by srkn** [pythonarcade/arcade#898]
Hi folk, 
I am trying to compile my game on macos and I noticed that arcade does not support this on macos (it works without problem on win/linux) What is reason behind this incompatibility? Does it have something to do with pymunk (chipmunk)? What could be done to overcome this?

**Comment by Cleptomania** [comment]
You can see the pyinstaller hook for Arcade here: https://github.com/pythonarcade/arcade/blob/development/arcade/__pyinstaller/hook-arcade.py

If you check that we're raising a NotImplementedError for Mac, I believe this is solely because we didn't have anyone with both the expertise/time/equipment to properly test it out there. I actually do have a Mac I can test out with, so I can give this a run maybe tonight or tomorrow, but here's a little bit of an explanation on what should theoretically need done for it to work.

The things that would need handled would be the resources directory, chipmunk, and ffmpeg. You'll notice that Windows/Linux do not include ffmpeg, that's because Mac is the only OS that requires ffmpeg. If you build without including these, everything should work but you might not have sound.

On Mac Arcade will try to use a system installed ffmpeg, and if it doesn't exist it will fallback to the included ffmpeg binaries, so this step would serve to ensure that all Mac users have working sound regardless of if they have ffmpeg installed or not.

The ffmpeg binaries are located in the `arcade/lib` folder.

As for the chipmunk binary, if you just do a `pip install arcade` and then find the chipmunk binary in the site-packages folder relative to the pyinstaller hook you can include that there the same way it's being done for the Windows/Linux versions.

Then the resources directory would need included, in the same way it's being done for Windows/Linux.

That really should be the only three things necessary to get it working on Mac:

- resources directory
- ffmpeg binaries
- chipmunk binary

Regardless, I'm going to make this part of the 2.6 release milestone, as it should actually be fairly trivial to implement.

**Comment by srkn** [comment]
I'll submit a PR regarding this, probably today, I did same things except ffmpeg part, so I'll include that too.

**Comment by pvcraven** [comment]
Going to close this in favor of tracking it with just Issue #754.
