### ISSUE TITLE
Child class doesn't inherit attribute 'color' from parent class 'SpriteSolidColor'

### ISSUE THREAD

**Issue by ErLa58** [pythonarcade/arcade#908]
Arcade 2.5.7 Win10
Child class inherits color (255,255,255) from SpriteSolidColor instead of the init color ('width' and 'height' are inherited correctly).
The draw method shows a correct color though.
See demo below. (The pasted code messes things up, that's why the added code screenshot)

```py
import arcade

class Rect(arcade.SpriteSolidColor):
	def __init__(self):
		super().__init__(75, 100, arcade.color.YELLOW)
		
class Win(arcade.Window):
	def __init__(self):
		super().__init__(400, 300, "Hit R key to change color")
		self.rect = Rect()
		self.rect.position = 200, 150
		# attribute color is white!
		print(f"init width height color {self.rect.width} {self.rect.height} {self.rect.color}")
		
	def on_draw(self):
		arcade.start_render()
		self.rect.draw()

	def on_key_press(self, key, key_modifiers):
		if key != arcade.key.R: return
		self.rect.color = arcade.color.RED
		print(f"on R key press width height color {self.rect.width} {self.rect.height} {self.rect.color}")
		self.rect.draw()
		
def main():
	win = Win()
	arcade.run()

if __name__ == "__main__":
	main()
```

![image](https://user-images.githubusercontent.com/85962761/124375715-ea15a880-dca3-11eb-9afe-6fb84f146bdc.png)

**Comment by einarf** [comment]
Thanks for the report. 

A simple way to paste code is in the following block (Those are backticks). This is standard markdown.
\`\`\`py
code here
\`\`\`

I fixed it in your post already.

**Comment by einarf** [comment]
I reverted the fix because it's actually reporting the right color. It might be a confusing thing.

There are two colors for a sprite:
1) The colors in the texture
2) The sprite color

These two colors are multiplied together to produce the final colors. That's why the sprite colors is white. `SpriteSolidColor` creates a sprite with a texture of the given color. That is the color in (1). The other color is then multiplied with the texture color... so again.. it should be white.

You can for example make a white `SpriteSolidColor` and use the color property to affect its white texture. For example `(255, 0, 0, 255)` will make it red or `(255, 255, 255, 127)` will make it semi transparent.

Maybe we should add something more in the docs about this?

**Comment by ErLa58** [comment]
@einarf : Thx for the explanation.
But how can one in this case query the color?
Initializing next to the super() explicitly the color in the Rect class above works, but seems strange.
So:
```
class Rect(arcade.SpriteSolidColor):
    def __init__(self):
        super().__init__(75, 100, arcade.color.YELLOW)
        self.color = arcade.color.YELLOW

```

**Comment by einarf** [comment]
> But how can one in this case query the color?

hmm. yes. It's confusing. Maybe we should call it `texture_color` and have a public property for that?

**Comment by ErLa58** [comment]
thx, fine by me

**Comment by pvcraven** [comment]
I get the confusion here. I don't think that we should make an API change for it though. Ideally, maybe a tint_color and a texture_color, but breaking code that depends on the current names would not be great.
