### ISSUE TITLE
Need O(1) way to clear a sprite list

### ISSUE THREAD

**Issue by pvcraven** [pythonarcade/arcade#911]
Per discord, user wants to clear sprite list, without popping off every sprite individually.

Creating a brand new sprite list does not work in their use-case.

While there is a SpriteList.clear() command it just throws a "not implemented" exception.

**Comment by pvcraven** [comment]
As sprites track what lists they are a part of, an O(1) operation may not be possible.

**Comment by einarf** [comment]
That is on my list. I don't know how possible it is, but worth exploring.

The problem is currently that we need to remove the spritelist reference from the sprite. We can do `O(1)` for static spritelists assuming this means static spritelists don't add a spritelist reference to the sprite itself. This means setting sprite properties will have no effect. The state of the original sprite is what sticks.

The other problem related to this is the circual reference between Sprite and SpriteList. If a SpriteList is not cleared all sprite and spritelist references will leak. Using WeakSets will severely affect the performance. Probably a 50% reduction.

**Comment by einarf** [comment]
An option is to add an optional spritelist argument to the setter functions for sprites.
```py
sprite.set_position(x, y, spritelist)
```
This updates the sprite in the specified spritelist only. A spritelist could also be configured to not register itself on a sprite meaning you would have to supply a spritelist every time you changed a property on your sprites.

This would make clear `O(1)` only having to re-create the internal dict/list/buffers.

It also means there are no circular references.

**Comment by einarf** [comment]
We now have a `clear()` menthod.

```py
# By default we do a deep clear interating sprites
spritelist.clear(deep=True)
# Advanced users can use `O(1)` clear if they meed the conditions
spritelist.clear(deep=False)
```

**Comment by einarf** [comment]
2.6.10 released
