### ISSUE TITLE
Arcade must support old GPU

### ISSUE THREAD

**Issue by streetartist** [pythonarcade/arcade#915]
I think arcade must support older GPU. Even big engines like Godot, Unity 3D and Pygame still support old GPU too. There are many computers using old GPU. Arcade must support them in order to have more users. You can imagine that if someone uses Arcade to make a game and then shares it with his friends, but his friends' computer can not run the game. He will be very very upset And Even never use Arcade any more. I think it is terrible. So Arcade must support old GPU.

**Comment by einarf** [comment]
Arcade is designed to be a modern python game library using GL 3.3 at a minimum. We rely too much on 3.3 features and supporting older opengl versions would be a complete rewrite.

BUT .. there might be things we can do to make arcade work with 3.1 drivers since most of those drivers do have a lot of the 3.3 features anyway. It's just not 3.3 feature complete. If you are willing to assist us in #914 there's still some hope.

If this doesn't bare any fruits there is always pyglet.
