### ISSUE TITLE
dev branch : global_options for TileMap

### ISSUE THREAD

**Issue by EnlNovius** [pythonarcade/arcade#921]
## Enhancement request:

Have a global_options option for the TileMap class that allows to set a default value to all layers that can be overridden by layer_options if needed.  

I have already set up an implementation, do I have to make a pull request? If not, I will propose an implementation here.

**Comment by EnlNovius** [comment]
Pull request sent =)

**Comment by Cleptomania** [comment]
This is merged in and a few minor adjustments to make it fit in better with the rest of the class and maintain a bit of backward compatibility.

The new order of attributes is `load_tilemap(map_file, scaling, layer_options, use_spatial_hash, hit_box_algorithm, hit_box_detail)`. Going with this order because a lot of example code already assumes that `scaling` is the second arg and `layer_options` is the third. This also makes sense as most use cases you probably don't want to enable things like spatial hash on every layer, or are happy with the defaults for hit box algorithm alg and detail.

Not saying this isn't useful though, there's definitely cases where this will save some code from the game's perspective.

Thanks for the suggestion and PR
