### ISSUE TITLE
Add on_update method to Scene class

### ISSUE THREAD

**Issue by bunny-therapist** [pythonarcade/arcade#982]
### What should be added/changed?
Add on_update(self, delta_time) method to Scene class which calls the same method for included sprite lists, with the same signature.

### What would it help with?
Spritelists, sprites, etc all have always had on_update method which accepts delta_time. New Scene class only has "update" and "update_animation". As it is, I would either have to switch to using "update" method of all sprites instead of "on_update", or use Scene.get_spritelist to get each spritelist and call its on_update method. (Note that on_update is vital if you want to be able to vary delta_time), but that makes the Scene class much less useful, simply adding extra calls.

**Comment by Cleptomania** [comment]
I've added the `delta_time` parameter to `Scene.on_update`. This doesn't break current API as it defaults to the same `1 / 60` that `SpriteList.on_update` does if it's not supplied.

**Comment by einarf** [comment]
> I've added the `delta_time` parameter to `Scene.on_update`. This doesn't break current API as it defaults to the same `1 / 60` that `SpriteList.on_update` does if it's not supplied.

Maybe better to set it to `None` or 0 by default? There can be some interesting bugs when framrates don't match 1/60.

**Comment by Cleptomania** [comment]
> Maybe better to set it to `None` or 0 by default? There can be some interesting bugs when framrates don't match 1/60.

Are you suggesting we change it in the SpriteList function? That’s what the default is in `SpriteList.on_update`

**Comment by einarf** [comment]
aha. With that in mind it makes sense. I guess this explains issues with general smoothness since we don't pass delta time in many of the examples. I'll see if I can clean that part up. We'll be off 1/4th of a frame very second ish and things will stutter if the frame time is lower for one frame.

It's more a problem with examples. We need to promote passing delta time.

EDIT: Actually, this needs to be looked into a bit more some time in the future. `update()` / `on_update()` and proper delta time would make games a lot smoother. It's not something we can just tack on right now.

I should also not mess around with issues when I'm sleep deprived 😄

**Comment by Cleptomania** [comment]
For the time being, I've added `on_update` support to Scene, though we should probably start talking about the difference between `update()` and `on_update()` and their usages in a separate issue. I foresee that being an API breaking thing though so not sure we're at a good point to do much about it yet.

**Comment by einarf** [comment]
2.6.4 released
